Attemp previous version of script to avoid creating a new tast revision on rollback.

diff --git a/.github/workflows/rollback-migrations.yml b/.github/workflows/rollback-migrations.yml
--- a/.github/workflows/rollback-migrations.yml
+++ b/.github/workflows/rollback-migrations.yml
@@ -14,15 +14,18 @@ env:
   AWS_REGION: ${{ vars.AWS_REGION }}
   ECS_CLUSTER_NAME: ${{ vars.AWS_ECS_CLUSTER_NAME }}
   TASK_DEFINITION_FAMILY: ${{ vars.AWS_MIGRATIONS_TASK_DEFINITION_FAMILY_NAME }}
-  SUBNET_IDS: ${{ vars.AWS_RUN_TASK_SUBNET_IDS }}
-  SECURITY_GROUP_ID: ${{ vars.AWS_RUN_TASK_SECURITY_GROUP_ID }}
-  CONTAINER_OVERRIDES: |
-    [
-      {
-        "name": "${{ vars.AWS_MIGRATIONS_CONTAINER_NAME }}",
-        "command": ["--downgradeToRevision=${{ inputs.downgradeToRevision }}"]
-      }
-    ]
+  NETWORK-CONFIGURATION: ${{ vars.AWS_NETWORK_CONFIGURATION }}
+  LOG_GROUP_NAME: ${{ vars.AWS_MIGRATIONS_LOG_GROUP_NAME }}
+  LOG_STREAM_PREFIX: ${{ vars.AWS_MIGRATIONS_LOG_STREAM_PREFIX }}
+  OVERRIDES: |
+    {
+      "containerOverrides": [
+        {
+          "name": "${{ vars.AWS_MIGRATIONS_CONTAINER_NAME }}",
+          "command": ["--downgradeToRevision=${{ inputs.downgradeToRevision }}"]
+        }
+      ]
+    }
 
 jobs:
   rollback-migrations:
@@ -36,79 +39,57 @@ jobs:
           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Download Task Definition
+      - name: Rollback Database Migrations
+        env:
         run: |
-          aws ecs describe-task-definition \
+          # Get the latest task definition ARN
+          TASK_DEF_ARN=$(aws ecs describe-task-definition \
             --task-definition $TASK_DEFINITION_FAMILY \
-            --query taskDefinition \
-            > task-definition.json
+            --query 'taskDefinition.taskDefinitionArn' \
+            --output text)
+          
+          # Start the migration task
+          TASK_ARN=$(aws ecs run-task \
+            --region $AWS_REGION \
+            --cluster $ECS_CLUSTER_NAME \
+            --task-definition $TASK_DEF_ARN \
+            --launch-type FARGATE \
+            --network-configuration "$NETWORK_CONFIGURATION" \
+            --overrides "$OVERRIDES" \
+            --query "tasks[0].taskArn" \
+            --output text)
+          TASK_ID=$(echo $TASK_ARN | awk -F/ '{print $NF}')
+          echo "Started migrations task: $TASK_ARN"
 
-      - name: Deploy ECS Task Definition
-        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
-        with:
-          task-definition: task-definition.json
-          cluster: ${{ env.ECS_CLUSTER_NAME }}
-          run-task: true
-          run-task-security-groups: ${{ env.SECURITY_GROUP_ID }}
-          run-task-subnets: ${{ env.SUBNET_IDS }}
-          run-task-assign-public-IP: DISABLED
-          run-task-container-overrides: ${{ env.CONTAINER_OVERRIDES }}
-          wait-for-task-stopped: true
+          # Wait until the task enters the STOPPED state
+          echo "Waiting for task to finish..."
+          aws ecs wait tasks-stopped \
+            --region $AWS_REGION  \
+            --cluster $ECS_CLUSTER_NAME \
+            --tasks "$TASK_ARN"
 
-#      - name: Rollback Database Migrations
-#        env:
-#          OVERRIDES: |
-#            {
-#              "containerOverrides": [
-#                {
-#                  "name": "${{ vars.AWS_MIGRATIONS_CONTAINER_NAME }}",
-#                  "command": ["--downgradeToRevision=${{ inputs.downgradeToRevision }}"]
-#                }
-#              ]
-#            }
-#        run: |
-#          # Start the migration task
-#          TASK_ARN=$(aws ecs run-task \
-#            --region ${{ vars.AWS_REGION }} \
-#            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
-#            --task-definition ${{ vars.AWS_MIGRATIONS_TASK_DEFINITION_NAME }} \
-#            --launch-type FARGATE \
-#            --network-configuration '${{ vars.AWS_NETWORK_CONFIGURATION }}' \
-#            --overrides "$OVERRIDES" \
-#            --query "tasks[0].taskArn" \
-#            --output text)
-#          TASK_ID=$(echo $TASK_ARN | awk -F/ '{print $NF}')
-#          echo "Started migrations task: $TASK_ARN"
-#          
-#          # Wait until the task enters the STOPPED state
-#          echo "Waiting for task to finish..."
-#          aws ecs wait tasks-stopped \
-#            --region ${{ vars.AWS_REGION }} \
-#            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
-#            --tasks "$TASK_ARN"
-#          
-#          # Wait 15 seconds for CloudWatch ingestion to finalize
-#          sleep 15
-#          
-#          # Output logs from the task
-#          echo "--- BEGIN MIGRATION LOGS ---"
-#          aws logs tail "${{ vars.AWS_MIGRATIONS_LOG_GROUP_NAME }}" \
-#            --region ${{ vars.AWS_REGION }} \
-#            --log-stream-name-prefix "${{ vars.AWS_MIGRATIONS_LOG_STREAM_PREFIX }}/$TASK_ID" \
-#            --format short
-#          echo "--- END MIGRATION LOGS ---"
-#          
-#          # Check if the task failed or was killed
-#          EXIT_CODE=$(aws ecs describe-tasks \
-#            --region ${{ vars.AWS_REGION }} \
-#            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
-#            --tasks "$TASK_ARN" \
-#            --query "tasks[0].containers[0].exitCode" \
-#            --output text)
-#          
-#          if [ "$EXIT_CODE" = "None" ] || [ "$EXIT_CODE" -ne 0 ]; then
-#            echo "Error: Migration failed or container was stopped prematurely. Exit code: $EXIT_CODE"
-#            exit 1
-#          fi
-#          
-#          echo "Task finished successfully!"
+          # Wait 15 seconds for CloudWatch ingestion to finalize
+          sleep 15
+
+          # Output logs from the task
+          echo "--- BEGIN MIGRATION LOGS ---"
+          aws logs tail "$LOG_GROUP_NAME" \
+            --region $AWS_REGION \
+            --log-stream-name-prefix "$LOG_STREAM_PREFIX/$TASK_ID" \
+            --format short
+          echo "--- END MIGRATION LOGS ---"
+
+          # Check if the task failed or was killed
+          EXIT_CODE=$(aws ecs describe-tasks \
+            --region $AWS_REGION \
+            --cluster $ECS_CLUSTER_NAME \
+            --tasks "$TASK_ARN" \
+            --query "tasks[0].containers[0].exitCode" \
+            --output text)
+
+          if [ "$EXIT_CODE" = "None" ] || [ "$EXIT_CODE" -ne 0 ]; then
+            echo "Error: Migration failed or container was stopped prematurely. Exit code: $EXIT_CODE"
+            exit 1
+          fi
+
+          echo "Task finished successfully!"
